import {Game,WORLD,UPGRADES,ITEMS,CHARACTERS,WORLDS,timeText} from './engine.mjs?v=4';
import {cactusPose,PART_RECTS} from './appearance.mjs?v=4';
import {ASSET_RECTS} from './asset-rects.mjs?v=4';
import {DesertAudio} from './audio.mjs';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d',{alpha:false}),overlay=$('overlay'),modal=$('modal');
const initialModal=modal.innerHTML,atlas=new Image(),modular=new Image(),players=new Image(),variants=new Image(),bossFrames=new Image(),enemyFrames=new Image(),relics=new Image();const assets={atlas,modular,players,variants,bossFrames,enemyFrames,relics};let selectedCharacter='saguaro',loaded=false,view={w:900,h:650},last=0,renderTime=0,hudClock=0,shake=0,sound=true,audio=new DesertAudio(),toastTimer,joy={x:0,y:0},particles=[],numbers=[],corpses=[],ghosts=[],keys=new Set(),lastDirection={x:0,y:1};const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let camera={x:WORLD.w/2,y:WORLD.h/2};
const game=new Game({event:onEvent});

const grains=Array.from({length:2600},()=>({x:Math.random()*WORLD.w,y:Math.random()*WORLD.h,l:1+Math.random()*4,a:.06+Math.random()*.08}));
function resize(){const r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);view={w:r.width,h:r.height};canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);game.view=view;}new ResizeObserver(resize).observe(canvas);
function playTone(freq=440,type='sine',length=.07,volume=.025){audio.tone(freq,type,length,volume);}
function burst(x,y,color,count=10){if(reduced)count=Math.min(count,3);for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,s=30+Math.random()*90;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,t:.3+Math.random()*.3,color});}if(particles.length>350)particles.splice(0,particles.length-350);}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),1800);}
function onEvent(type,data){
 audio.effect(type==='pickup'?(data==='gold'?'gold':'pickup'):type);
 if(type==='boost'){toast(({speed:'VITESSE',haste:'FRÉNÉSIE',damage:'PUISSANCE'})[data.kind]+' · 20 S');burst(game.player.x,game.player.y,'#d7ffa1',24);}if(type==='magnet'){toast('AIMANT · TOUTE L’XP ARRIVE');burst(game.player.x,game.player.y,'#93edf5',30);}if(type==='level'){keys.clear();showUpgrades();}
 if(type==='chosen'){overlay.hidden=true;refreshLoadout();updateHud();toast(data.newCombos.length?'COMBO : '+data.newCombos.map(c=>c.name).join(' + '):UPGRADES.find(u=>u.id===data.id).name);}
 if(type==='hit'){if(numbers.length<55)numbers.push({...data,t:.65,dx:(Math.random()-.5)*20});burst(data.x,data.y,'#fff4b9',3);}
 if(type==='kill'){burst(data.x,data.y,data.kind===2?'#ccb57a':'#974753',14);corpses.push({...data,t:.45});}
 if(type==='hurt'){shake=reduced?0:9;burst(game.player.x,game.player.y,'#90d8e5',16);}
 if(type==='dash'){burst(game.player.x,game.player.y,'#dcf99b',18);ghosts.push({x:game.player.x,y:game.player.y,t:.3});}
 if(type==='boss'){toast(game.world().boss.toUpperCase()+' ARRIVE');$('bossHud').hidden=false;shake=reduced?0:12;}
 if(type==='bloom'){burst(data.x,data.y,'#f985b2',18);shake=reduced?0:Math.max(shake,2);}
 if(type==='stone')burst(data.x,data.y,'#f4d29c',4);
 if(type==='poor')toast(`Il manque ${data.price-data.gold} pièces pour ce coffre.`);
 if(type==='chest'){keys.clear();joy={x:0,y:0};burst(data.x,data.y,'#ffe573',25);refreshLoadout();updateHud();showLoot(data);}
 if(type==='continueLoot'){overlay.hidden=true;toast('OBJET ÉQUIPÉ · '+game.openedChests+' COFFRE'+(game.openedChests>1?'S':''));}
 if(type==='dead'||type==='won'){updateHud();showResults(type==='won');}
 if(type==='worldClear'){keys.clear();joy={x:0,y:0};showWorldClear(data);updateHud();}if(type==='worldStart'){overlay.hidden=true;particles=[];numbers=[];corpses=[];ghosts=[];camera={x:game.player.x,y:game.player.y};updateHud();toast(game.world().name.toUpperCase());}if(type==='heal'){burst(data.x,data.y,'#cbf885',18);toast('+'+data.value+' PV');audio.effect('pickup');}if(type==='bossSpell'){$('spellLabel').textContent=data.name;$('spellLabel').classList.add('show');setTimeout(()=>$('spellLabel').classList.remove('show'),1300);}if(type==='start'){overlay.hidden=true;particles=[];numbers=[];corpses=[];ghosts=[];camera={x:game.player.x,y:game.player.y};refreshLoadout();$('bossHud').hidden=true;updateHud();$('pause').textContent='Ⅱ';audio.beat=0;audio.beatClock=0;}
}
function start(){if(!loaded)return;keys.clear();joy={x:0,y:0};audio.unlock().catch(()=>{});audio.setEnabled(sound);game.start(selectedCharacter);}
function itemStyle(item){return item.art===undefined?`background-position:${item.sprite%4*100/3}% ${Math.floor(item.sprite/4)*100/3}%`:`background-image:url(item-relics.png?v=4);background-size:800% 400%;background-position:${item.art%8*100/7}% ${Math.floor(item.art/8)*100/3}%`;}
function showLoot(item){
 overlay.hidden=false;modal.className='panel loot-panel';
 modal.innerHTML=`<div class="eyebrow">COFFRE OUVERT · ${item.price} PIÈCES</div><div class="loot-image" style="${itemStyle(item)}"></div><h2>${item.name}</h2><p>${item.desc}</p><div class="loot-meta">ÉQUIPÉ · NIVEAU ${item.level} / ${item.max}</div>${item.newCombos.map(c=>`<div class="combo-reveal"><b>✦ ${c.name}</b><p>${c.desc}</p></div>`).join('')}<button class="primary" id="keepItem">CONTINUER <span>↵</span></button><p class="next-price">Prochain coffre : ${game.chestPrice()} pièces.</p>`;
 $('keepItem').onclick=()=>game.continueLoot();$('keepItem').focus({preventScroll:true});
}
function bindStart(){const b=$('start');if(!b)return;b.disabled=!loaded;b.textContent=loaded?'LANCER L’EXPÉDITION  ↵':'PRÉPARATION DES MONDES…';b.onclick=start;const chooser=$('characterSelect');if(chooser){chooser.innerHTML=CHARACTERS.map(c=>`<button class="character-card ${selectedCharacter===c.id?'selected':''}" data-character="${c.id}" aria-pressed="${selectedCharacter===c.id}"><span class="character-portrait" style="background-position:0 ${c.row*100/3}%"></span><b>${c.name}</b><small>${c.hp} PV</small></button>`).join('');chooser.querySelectorAll('button').forEach(button=>button.onclick=()=>{selectedCharacter=button.dataset.character;game.characterId=selectedCharacter;game.reset();bindStart();updateHud();refreshLoadout();});$('characterDesc').textContent=CHARACTERS.find(c=>c.id===selectedCharacter).desc;}}
bindStart();let readyCount=0;const sources={atlas:'sprites.png',modular:'modular.png',players:'player-motion.png?v=4',variants:'variant-parts.png',bossFrames:'boss-movement.png?v=4',enemyFrames:'enemy-movement.png?v=4',relics:'item-relics.png?v=4'};for(const [key,img] of Object.entries(assets)){img.onload=()=>{readyCount++;if(readyCount===7){skinCache.clear();loaded=true;bindStart();}};img.onerror=()=>{const b=$('start');if(b){b.disabled=true;b.textContent='IMAGES INDISPONIBLES — RECHARGER';}};img.src=sources[key];}
function showWorldClear(data){overlay.hidden=false;modal.className='panel world-clear';modal.innerHTML=`<div class="eyebrow">MONDE ${data.completed+1} TERMINÉ</div><h2>${data.world.boss.toUpperCase()} EST VAINCU.</h2><p>Tu conserves tes objets, ton or et tes mutations. Récupère 30 % de ta vie maximum en entrant dans le prochain monde.</p><div class="next-world"><small>PROCHAINE ÉTAPE · MONDE ${data.completed+2}</small><strong>${data.next.name}</strong><span>Boss : ${data.next.boss}</span></div><button id="nextWorld" class="primary">ENTRER DANS LE MONDE SUIVANT</button>`;$('nextWorld').onclick=()=>game.nextWorld();$('nextWorld').focus({preventScroll:true});}
function showUpgrades(){overlay.hidden=false;modal.className='panel upgrade-panel';modal.innerHTML=`<div class="eyebrow">NIVEAU ${game.level} · MUTATION DISPONIBLE</div><h2>ÇA COMMENCE À PIQUER.</h2><p>Choisis une mutation. Le désert peut attendre.</p><div class="choices">${game.choices.map((u,i)=>`<button class="upgrade-card" data-upgrade="${u.id}"><span class="upgrade-icon">${u.icon}</span><b>${u.name}</b><p>${u.desc}</p><small>${game.count(u.id)?`NIV. ${game.count(u.id)+1}`:'NOUVEAU'} · ${i+1}</small></button>`).join('')}</div><div class="choice-note">Clique sur une carte ou appuie sur 1, 2 ou 3.</div>`;modal.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>game.choose(b.dataset.upgrade));requestAnimationFrame(()=>modal.querySelector('button')?.focus({preventScroll:true}));}
function togglePause(){if(game.pause()){keys.clear();joy={x:0,y:0};overlay.hidden=false;modal.className='panel';modal.innerHTML='<div class="eyebrow">UN PEU D’OMBRE</div><h2>LE DÉSERT ATTENDRA.</h2><p>Ton cactus reprend son souffle.</p><button id="resume" class="primary">REPRENDRE LA PARTIE <span>↵</span></button><button id="restart" class="secondary">Recommencer</button>';$('resume').onclick=()=>{game.resume();overlay.hidden=true;$('pause').textContent='Ⅱ';};$('restart').onclick=start;$('pause').textContent='▶';$('resume').focus({preventScroll:true});}else if(game.resume()){overlay.hidden=true;$('pause').textContent='Ⅱ';}}
function showResults(won){keys.clear();joy={x:0,y:0};overlay.hidden=false;modal.className='panel';modal.innerHTML=`<div class="eyebrow">${won?'LES TROIS MONDES SONT À TOI':'MONDE '+(game.worldIndex+1)+' · EXPÉDITION TERMINÉE'}</div><h2>${won?'CACTUS MAXIMUS.':'ÇA SENT LE SAPIN.'}</h2><p>${won?'Les trois gardiens sont tombés. Ton cactus a traversé les trois mondes.':'Même les plus belles épines ont besoin d’une seconde chance.'}</p><div class="result-stats"><div><strong>${timeText(game.time)}</strong><span>SURVIE</span></div><div><strong>${game.kills}</strong><span>ÉLIMINATIONS</span></div><div><strong>${game.level}</strong><span>NIVEAU</span></div></div><button id="again" class="primary">${won?'UNE AUTRE EXPÉDITION':'REPRENDRE RACINE'} <span>↵</span></button><button id="home" class="secondary">Retour à l’accueil</button>`;$('again').onclick=start;$('home').onclick=()=>{game.reset();modal.className='panel intro';modal.innerHTML=initialModal;bindStart();refreshLoadout();updateHud();$('bossHud').hidden=true;};$('again').focus({preventScroll:true});}
function refreshLoadout(){const entries=UPGRADES.filter(u=>game.count(u.id));$('buildCount').textContent=`${entries.length} MUTATION${entries.length!==1?'S':''}`;$('loadout').innerHTML=`<div class="loadout-item"><span class="item-icon">╱</span><div><b>Épines</b><small>${Math.round((18+game.item('barbs')*4+game.item('lens')*5)*game.multiplier())} dégâts · ${game.attackInterval().toFixed(2)} s</small></div><span class="item-level">1</span></div>`+entries.map(u=>`<div class="loadout-item"><span class="item-icon">${u.icon}</span><div><b>${u.name}</b></div><span class="item-level">${game.count(u.id)}</span></div>`).join('')+(!entries.length?'<p class="empty-build">Récolte les gouttes d’eau pour choisir tes mutations.</p>':'');
 const owned=ITEMS.filter(i=>game.item(i.id));$('inventory').innerHTML=owned.length?owned.map(i=>`<div class="loadout-item"><span class="item-art" style="${itemStyle(i)}"></span><div><b>${i.name}</b><small>${i.desc}</small></div><span class="item-level">${game.item(i.id)}</span></div>`).join(''):'<p class="empty-build">Ouvre les coffres avec l’or des ennemis.</p>';
 $('combos').innerHTML=game.combos().map(c=>`<div class="combo-tag"><b>✦ ${c.name}</b><small>${c.desc}</small></div>`).join('');
}
function updateHud(){const p=game.player;$('buffs').innerHTML=Object.entries(game.buffs).filter(([,v])=>v>0).map(([k,v])=>`<span class="buff ${k}">${({speed:'VITESSE',haste:'FRÉNÉSIE',damage:'DÉGÂTS'})[k]} · ${Math.ceil(v)} s</span>`).join('');$('healthText').textContent=`${Math.ceil(p.hp)} / ${p.maxHp}`;$('healthFill').style.width=`${p.hp/p.maxHp*100}%`;$('healthFill').style.background=p.hp/p.maxHp<.25?'#ee697d':'#c5ff65';$('timer').textContent=timeText(game.time);$('levelText').textContent=`NIV. ${game.level}`;$('xpFill').style.width=`${Math.min(100,game.xp/game.nextXp*100)}%`;$('kills').textContent=game.kills.toLocaleString('fr-FR');$('damageDone').textContent=Math.floor(game.damageDone).toLocaleString('fr-FR');$('timeFill').style.width=`${Math.min(100,game.stageTime/game.world().bossTime*100)}%`;$('dashFill').style.width=`${(1-game.dashCd/Math.max(2,4-game.item('feather')*.45))*100}%`;$('dashTouch').style.opacity=game.dashCd>0?'.45':'1';$('waveLabel').textContent=`${game.worldIndex+1} / 3 · ${game.world().name.toUpperCase()}`;$('worldName').textContent=game.world().name;$('bossCountdown').textContent=timeText(game.world().bossTime);$('bossName').textContent=game.world().boss;const boss=game.enemies.find(e=>e.kind===4);if(boss){$('bossFill').style.width=`${Math.max(0,boss.hp/boss.maxHp*100)}%`;$('bossText').textContent=Math.ceil(boss.hp);}else $('bossHud').hidden=true;$('goldCount').textContent=game.gold.toLocaleString('fr-FR');$('chestPrice').textContent=game.chestPrice();$('chestsCount').textContent=game.openedChests;const c=game.nearestChest(),near=c&&Math.hypot(c.x-p.x,c.y-p.y)<100;$('interact').hidden=!near||game.status!=='playing';$('interact').textContent=`E · OUVRIR ${game.chestPrice()} ◉`;$('interact').classList.toggle('poor',game.gold<game.chestPrice());$('chestTouch').hidden=!near||game.status!=='playing';}
function sprite(index,x,y,size,angle=0,flip=1,alpha=1){if(!loaded)return;ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.scale(flip,1);ctx.globalAlpha*=alpha;const cw=atlas.width/4,ch=atlas.height/2;ctx.drawImage(atlas,(index%4)*cw,Math.floor(index/4)*ch,cw,ch,-size/2,-size/2,size,size);ctx.restore();}
function part(index,x,y,w,h,angle=0,ax=.5,ay=.5){if(!loaded)return;const [sx,sy,sw,sh]=PART_RECTS[index];ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.drawImage(modular,sx,sy,sw,sh,-w*ax,-h*ay,w,h);ctx.restore();}
const skinCache=new Map();
function framed(image,rect,x,y,w,h,angle=0,ax=.5,ay=.5){if(!loaded)return;ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.drawImage(image,...rect,-w*ax,-h*ay,w,h);ctx.restore();}
function torsoSkin(index){if(!loaded)return null;const armor=game.item('armor')+game.item('shell')+game.item('anchor'),toxic=game.item('venom')+game.item('mushroom'),fire=game.item('sun')+game.item('ember')+game.item('chili'),crystal=game.item('ice')+game.item('quartz');const key=[index,armor,toxic,fire,crystal].join(':');if(skinCache.has(key))return skinCache.get(key);const c=document.createElement('canvas');c.width=128;c.height=176;const g=c.getContext('2d');g.drawImage(players,...ASSET_RECTS['player-motion'][index],0,0,128,176);g.save();g.globalCompositeOperation='source-atop';g.beginPath();g.rect(0,108,128,68);g.clip();if(armor){g.globalAlpha=Math.min(.95,.7+armor*.04);g.drawImage(modular,...PART_RECTS[4],-12,102,152,80);}if(toxic){g.globalAlpha=.25;g.fillStyle='#9b3cbf';g.fillRect(0,110,128,66);}if(fire){g.globalAlpha=.17;g.fillStyle='#ff913d';g.fillRect(0,148,128,28);}if(crystal){g.globalAlpha=.8;for(let i=0;i<3;i++)g.drawImage(modular,...PART_RECTS[6],26+i*28,124+(i%2)*8,15,27);}g.restore();skinCache.set(key,c);if(skinCache.size>80)skinCache.delete(skinCache.keys().next().value);return c;}
function armSkin(index){const armor=game.item('armor')+game.item('shell')+game.item('anchor'),key='arm:'+index+':'+armor+':'+game.characterId;if(skinCache.has(key))return skinCache.get(key);const c=document.createElement('canvas');c.width=128;c.height=128;const g=c.getContext('2d');g.filter=game.characterId==='luna'?'hue-rotate(85deg) saturate(1.2)':game.characterId==='fero'?'hue-rotate(-20deg)':game.characterId==='opuntia'?'brightness(1.12) saturate(.8)':'none';g.drawImage(variants,...ASSET_RECTS['variant-parts'][index],0,0,128,128);g.filter='none';if(armor&&index>=4){g.save();g.globalCompositeOperation='source-atop';g.beginPath();g.rect(0,83,128,45);g.clip();g.globalAlpha=.85;g.drawImage(modular,...PART_RECTS[4],-12,78,152,65);g.restore();}skinCache.set(key,c);if(skinCache.size>80)skinCache.delete(skinCache.keys().next().value);return c;}
function drawCactus(x,y,alpha=1){if(!loaded)return;const pose=cactusPose(game,renderTime,reduced);ctx.save();ctx.translate(x,y+pose.bob);ctx.rotate(pose.lean);ctx.scale(game.player.facing*pose.scale,pose.scale);ctx.globalAlpha=alpha;for(const p of pose.parts){if(p.atlas==='players'){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.angle);ctx.drawImage(torsoSkin(p.index),-p.w*p.ax,-p.h*p.ay,p.w,p.h);ctx.restore();}else if(p.atlas==='variants'){if(p.index<8){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.angle);ctx.drawImage(armSkin(p.index),-p.w*p.ax,-p.h*p.ay,p.w,p.h);ctx.restore();}else framed(variants,ASSET_RECTS['variant-parts'][p.index],p.x,p.y,p.w,p.h,p.angle,p.ax,p.ay);}else if(p.atlas==='relics')framed(relics,ASSET_RECTS['item-relics'][p.index],p.x,p.y,p.w,p.h,p.angle,p.ax,p.ay);else part(p.index,p.x,p.y,p.w,p.h,p.angle,p.ax,p.ay);}ctx.restore();}
function shadow(x,y,size,alpha=.16){ctx.fillStyle=`rgba(55,45,32,${alpha})`;ctx.beginPath();ctx.ellipse(x,y+size*.31,size*.35,size*.13,0,0,Math.PI*2);ctx.fill();}
function screen(x,y){return {x:x-camera.x+view.w/2,y:y-camera.y+view.h/2};}
function visible(x,y,pad=100){const p=screen(x,y);return p.x>-pad&&p.y>-pad&&p.x<view.w+pad&&p.y<view.h+pad;}
function draw(dt){const active=game.status==='playing';if(active||game.status==='ready')renderTime+=dt;camera.x+=(game.player.x-camera.x)*Math.min(1,dt*10);camera.y+=(game.player.y-camera.y)*Math.min(1,dt*10);const halfW=Math.min(view.w/2,WORLD.w/2),halfH=Math.min(view.h/2,WORLD.h/2);camera.x=Math.max(halfW,Math.min(WORLD.w-halfW,camera.x));camera.y=Math.max(halfH,Math.min(WORLD.h-halfH,camera.y));ctx.save();if(shake>0){ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake=Math.max(0,shake-dt*18);}ctx.fillStyle=game.world().color;ctx.fillRect(0,0,view.w,view.h);ctx.save();ctx.translate(view.w/2-camera.x,view.h/2-camera.y);
 for(const z of game.terrain){if(!visible(z.x,z.y,z.r+20))continue;const art=z.kind==='ice'?29:z.kind==='lava'?30:28;framed(relics,ASSET_RECTS['item-relics'][art],z.x,z.y,z.kind==='rough'?z.r*.85:z.r*2,z.kind==='rough'?z.r*.65:z.r*1.6);if(z.kind==='lava'){ctx.save();ctx.globalAlpha=.15+Math.sin(renderTime*2+z.x)*.05;ctx.fillStyle='#ffa33f';ctx.beginPath();ctx.ellipse(z.x,z.y,z.r*.72,z.r*.55,0,0,Math.PI*2);ctx.fill();ctx.restore();}if(z.kind==='ice'){ctx.strokeStyle='#e4fbff66';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(z.x,z.y,z.r*.85,z.r*.65,0,0,Math.PI*2);ctx.stroke();}}
 for(let i=0;i<260;i++){const x=80+(i*863)%5640,y=80+(i*1297)%4440;if(!visible(x,y,25))continue;ctx.save();ctx.globalAlpha=game.worldIndex===0?.55:.23;framed(relics,ASSET_RECTS['item-relics'][31],x,y,12+i%17,9+i%11);ctx.restore();}
 for(const g of grains){if(!visible(g.x,g.y,5))continue;ctx.strokeStyle=`rgba(96,63,34,${g.a})`;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(g.x,g.y);ctx.lineTo(g.x+g.l,g.y+g.l*.3);ctx.stroke();}
 ctx.strokeStyle='#88663955';ctx.lineWidth=3;ctx.setLineDash([8,12]);ctx.strokeRect(20,20,WORLD.w-40,WORLD.h-40);ctx.setLineDash([]);
 for(const c of game.chests){if(!visible(c.x,c.y,80))continue;shadow(c.x,c.y,53,.17);if(c.opened)framed(variants,ASSET_RECTS['variant-parts'][8],c.x,c.y-5,48,43);else part(12,c.x,c.y-5,48,43);if(!c.opened){ctx.textAlign='center';ctx.font='bold 12px "Space Grotesk",Arial';ctx.fillStyle='#fff4b4';ctx.strokeStyle='#5a411a';ctx.lineWidth=3;ctx.strokeText(game.chestPrice()+' ◉',c.x,c.y-37);ctx.fillText(game.chestPrice()+' ◉',c.x,c.y-37);const pulse=reduced?1:.65+Math.sin(renderTime*3+c.x)*.25;ctx.globalAlpha=pulse;ctx.strokeStyle='#f8e286';ctx.lineWidth=1.5;ctx.beginPath();ctx.ellipse(c.x,c.y+15,27,8,0,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1;}}
 for(const plant of game.healPlants){if(plant.used||!visible(plant.x,plant.y,30))continue;shadow(plant.x,plant.y,24,.12);framed(variants,ASSET_RECTS['variant-parts'][9],plant.x,plant.y-4,18,24);ctx.fillStyle='#dbf6c8';ctx.font='bold 12px Arial';ctx.textAlign='center';ctx.fillText('+',plant.x,plant.y-22);}
 for(const h of game.hazards){ctx.save();ctx.strokeStyle=h.color||game.world().accent;ctx.fillStyle=h.warning>0?'#ef556b33':'#fb935975';ctx.lineWidth=3;if(h.kind==='line'){ctx.setLineDash([9,7]);ctx.beginPath();ctx.moveTo(h.x,h.y);ctx.lineTo(h.x2,h.y2);ctx.stroke();}else{ctx.beginPath();ctx.arc(h.x,h.y,h.r,0,Math.PI*2);ctx.fill();ctx.stroke();if(h.warning>0){ctx.beginPath();ctx.arc(h.x,h.y,h.r+5,0,Math.PI*2*(1-Math.min(1,h.warning)));ctx.stroke();}}ctx.restore();}
 if(game.status==='ready'){for(let i=0;i<7;i++){const a=i*Math.PI*2/7;const x=WORLD.w/2+Math.cos(a)*300,y=WORLD.h/2+Math.sin(a)*200;sprite(1+i%4,x,y,55,Math.sin(renderTime+i)*.06);} }
 for(const d of game.drops){if(!visible(d.x,d.y,20))continue;const float=reduced?0:Math.sin(renderTime*3+d.x)*2;if(['magnet','speed','haste','damage'].includes(d.kind)){const art={magnet:24,speed:25,haste:26,damage:27}[d.kind];shadow(d.x,d.y,24,.12);framed(relics,ASSET_RECTS['item-relics'][art],d.x,d.y+float,25,28);ctx.strokeStyle=d.kind==='magnet'?'#ffed84':'#e9fff7';ctx.lineWidth=1.5;ctx.beginPath();ctx.ellipse(d.x,d.y+16,17,5,0,0,Math.PI*2);ctx.stroke();continue;}if(d.kind==='gold'){ctx.save();ctx.translate(d.x,d.y+float);const width=11*(.6+Math.abs(Math.sin(renderTime*3+d.x))*.4);part(14,0,0,width,12);ctx.restore();continue;}ctx.save();ctx.translate(d.x,d.y+float);ctx.fillStyle=d.kind==='heal'?'#b5e15e':'#74d7e1';ctx.strokeStyle=d.kind==='heal'?'#476028':'#337384';ctx.lineWidth=1.5;ctx.beginPath();if(d.kind==='heal')ctx.roundRect(-5,-5,10,10,2);else{ctx.moveTo(0,-7);ctx.quadraticCurveTo(10,3,0,7);ctx.quadraticCurveTo(-10,3,0,-7);}ctx.fill();ctx.stroke();if(d.value>3&&d.kind==='xp'){ctx.fillStyle='#eaffff';ctx.fillRect(-1,-1,2,3);}ctx.restore();}
 for(const corpse of corpses){if(active)corpse.t-=dt;ctx.save();ctx.globalAlpha=Math.max(0,corpse.t/.45);ctx.translate(corpse.x,corpse.y);ctx.rotate((.45-corpse.t)*3);ctx.scale(1+(.45-corpse.t)*.6,Math.max(.2,corpse.t/.45));if(corpse.kind===4)framed(bossFrames,ASSET_RECTS['boss-movement'][corpse.worldIndex*8+7],0,0,145,138);else framed(enemyFrames,ASSET_RECTS['enemy-movement'][(corpse.worldIndex*4+corpse.kind)*8+7],0,0,53,53);ctx.restore();}corpses=corpses.filter(c=>c.t>0);
 for(const ghost of ghosts){if(active)ghost.t-=dt;drawCactus(ghost.x,ghost.y,Math.max(0,ghost.t)*.7);}ghosts=ghosts.filter(g=>g.t>0);if(game.dashTime>0&&!reduced&&ghosts.length<9)ghosts.push({x:game.player.x,y:game.player.y,t:.18});
 for(const r of game.rings){ctx.strokeStyle=r.color;ctx.globalAlpha=r.ttl/r.max;ctx.lineWidth=4;ctx.beginPath();ctx.arc(r.x,r.y,r.r*(1-r.ttl/r.max*.3),0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1;}
 const p=game.player;if(game.count('sand')){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(renderTime*.7);ctx.strokeStyle='#fbf1c277';ctx.lineWidth=3;const radius=70+game.count('sand')*20;for(let i=0;i<4;i++){ctx.beginPath();ctx.arc(0,0,radius,i*Math.PI/2,i*Math.PI/2+.85);ctx.stroke();}ctx.restore();}
 const actors=[...game.enemies.map(e=>({...e,isPlayer:false})),...game.obstacles.map(o=>({...o,isObstacle:true})),{...p,isPlayer:true}].sort((a,b)=>a.y-b.y);
 for(const e of actors){if(!visible(e.x,e.y,140))continue;
 if(e.isObstacle){shadow(e.x,e.y,e.size,.19);if(game.worldIndex===0)sprite(7,e.x,e.y-e.size*.15,e.size);else framed(variants,ASSET_RECTS['variant-parts'][game.worldIndex===1?10:11],e.x,e.y-e.size*.15,e.size*.85,e.size*.85);continue;}
 if(e.isPlayer){shadow(e.x,e.y-(60+game.count('branch')*7)*.31+3,60+game.count('branch')*7);const alpha=e.inv>0&&Math.floor(renderTime*18)%2===0?.45:1;drawCactus(e.x,e.y,alpha);if(e.growth>0){ctx.strokeStyle='#c5ff65';ctx.globalAlpha=e.growth;ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(e.x,e.y+10,35+(1-e.growth)*30,12+(1-e.growth)*12,0,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1;}}
 else{const size=e.kind===4?145:e.kind===3?66:53;shadow(e.x,e.y,size,e.kind===3?.09:.16);const phase=renderTime*(e.kind===4?7:11)+e.phase,step=reduced?0:Math.sin(phase);ctx.save();ctx.translate(e.x,e.y+(e.kind===3?-24+step*7:-Math.abs(step)*2));if(!reduced)ctx.scale(1+step*.055+(e.recoil||0)*.5,1-step*.04-(e.recoil||0)*.35);if(e.flash>0)ctx.filter='brightness(1.7)';const angle=e.kind===2?renderTime*(e.x<p.x?3:-3):step*.065;if(e.kind===4){const state=e.pendingSpell?(e.pendingSpell.wait>.4?4:5):e.chargeTime>0?6:e.castTime>.2?6:e.castTime>0?7:Math.floor(e.motion||0)%4;framed(bossFrames,ASSET_RECTS['boss-movement'][e.bossRow*8+state],0,0,size,size*.95,angle);}else{const close=Math.hypot(e.x-p.x,e.y-p.y)<e.r+p.r+25,frame=reduced?0:Math.floor(e.motion||0)%8;framed(enemyFrames,ASSET_RECTS['enemy-movement'][(e.worldIndex*4+e.kind)*8+frame],0,0,size,size,angle);}ctx.restore();if(e.slow>0){ctx.strokeStyle='#4d803f';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(e.x,e.y+16,20,7,0,0,Math.PI*2);ctx.stroke();}if(e.burn>0){ctx.strokeStyle='#f5ae40';ctx.lineWidth=3;ctx.beginPath();ctx.arc(e.x,e.y,20,renderTime*4,renderTime*4+4);ctx.stroke();}if(e.hp<e.maxHp&&e.kind!==4){ctx.fillStyle='#3d332d';ctx.fillRect(e.x-15,e.y-size*.5-5,30,3);ctx.fillStyle='#ad483d';ctx.fillRect(e.x-15,e.y-size*.5-5,30*Math.max(0,e.hp/e.maxHp),3);}}
 }
 for(const bolt of game.bolts){ctx.save();ctx.globalAlpha=bolt.ttl/.18;ctx.strokeStyle='#faf2a1';ctx.lineWidth=3;ctx.shadowBlur=10;ctx.shadowColor='#f7ce54';for(const b of bolt.segments){ctx.beginPath();ctx.moveTo(b.x1,b.y1);ctx.lineTo((b.x1+b.x2)/2+Math.sin(renderTime*70)*9,(b.y1+b.y2)/2+Math.cos(renderTime*70)*9);ctx.lineTo(b.x2,b.y2);ctx.stroke();}ctx.restore();}
 for(const f of game.fields){if(!visible(f.x,f.y,160))continue;const art={bomb:3,meteor:15,geyser:19,poison:17,boomerang:2}[f.kind];ctx.save();if(f.kind==='poison')ctx.globalAlpha=.3;const size=f.kind==='poison'?f.r*1.7:f.kind==='meteor'?32:28;if(f.kind==='meteor'||f.kind==='geyser'){ctx.strokeStyle=f.kind==='meteor'?'#f39662':'#8ae4d7';ctx.setLineDash([5,6]);ctx.beginPath();ctx.arc(f.x,f.y,f.r,0,Math.PI*2);ctx.stroke();}framed(relics,ASSET_RECTS['item-relics'][art],f.x,f.y-(f.kind==='meteor'?f.ttl*140:0),size,size,f.kind==='boomerang'?renderTime*14:0);ctx.restore();}
 for(const s of game.shots){if(s.kind==='bubble'||s.kind==='comet'){framed(relics,ASSET_RECTS['item-relics'][s.kind==='bubble'?1:5],s.x,s.y,s.kind==='bubble'?25:32,s.kind==='bubble'?25:32,Math.atan2(s.vy,s.vx));}else if(s.kind==='flower'){sprite(6,s.x,s.y,30,renderTime*4);}else{ctx.save();ctx.translate(s.x,s.y);ctx.rotate(Math.atan2(s.vy,s.vx));ctx.strokeStyle='#446332';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-10,0);ctx.lineTo(5,0);ctx.stroke();ctx.fillStyle='#faffcc';ctx.beginPath();ctx.moveTo(9,0);ctx.lineTo(1,-3);ctx.lineTo(1,3);ctx.closePath();ctx.fill();ctx.restore();}}
 for(const s of game.hostile){ctx.fillStyle=s.color||'#9f3452';ctx.strokeStyle='#fbe88a';ctx.lineWidth=2;ctx.beginPath();ctx.arc(s.x,s.y,7,0,Math.PI*2);ctx.fill();ctx.stroke();}
 if(game.item('seed'))for(let i=0;i<game.item('seed');i++){const angle=game.time*2.8+i*Math.PI*2/game.item('seed');framed(variants,ASSET_RECTS['variant-parts'][12],p.x+Math.cos(angle)*75,p.y+Math.sin(angle)*75,23,23,renderTime*2);}
 if(game.item('satellite'))for(let i=0;i<game.item('satellite');i++){const a=game.time*2+i*Math.PI*2/game.item('satellite');framed(relics,ASSET_RECTS['item-relics'][16],p.x+Math.cos(a)*110,p.y+Math.sin(a)*110,24,24,a);}
 if(game.item('mushroom')){ctx.strokeStyle='#b278c177';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,90,0,Math.PI*2);ctx.stroke();}
 const moving=game.status==='playing';for(const part of particles){if(moving){part.x+=part.vx*dt;part.y+=part.vy*dt;part.t-=dt;}ctx.globalAlpha=Math.max(0,part.t*2);ctx.fillStyle=part.color;ctx.fillRect(part.x,part.y,3,3);}ctx.globalAlpha=1;particles=particles.filter(p=>p.t>0);
 ctx.textAlign='center';ctx.font='bold 14px "Space Grotesk",Arial';for(const n of numbers){if(moving)n.t-=dt;ctx.globalAlpha=Math.max(0,n.t/.6);ctx.fillStyle=n.boss?'#f6ffbb':'#fff4d7';ctx.strokeStyle='#423921';ctx.lineWidth=3;const y=n.y-20-(.6-n.t)*45;ctx.strokeText(n.amount,n.x+n.dx,y);ctx.fillText(n.amount,n.x+n.dx,y);}ctx.globalAlpha=1;numbers=numbers.filter(n=>n.t>0);ctx.restore();if(game.status==='playing'){const guideBoss=game.enemies.find(e=>e.kind===4),c=guideBoss||game.nearestChest();if(c){const target=screen(c.x,c.y),out=target.x<40||target.y<140||target.x>view.w-40||target.y>view.h-45;if(out){const vx=target.x-view.w/2,vy=target.y-view.h/2,len=Math.hypot(vx,vy)||1,scale=Math.min((view.w/2-35)/Math.max(1,Math.abs(vx)),(view.h/2-105)/Math.max(1,Math.abs(vy))),x=view.w/2+vx*scale,y=view.h/2+vy*scale;ctx.save();ctx.translate(x,y);ctx.rotate(Math.atan2(vy,vx));ctx.fillStyle='#ffe593';ctx.strokeStyle='#57442d';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(10,0);ctx.lineTo(-6,-6);ctx.lineTo(-6,6);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();ctx.font='bold 12px Arial';ctx.textAlign='center';ctx.fillStyle='#ffe593';ctx.strokeStyle='#57442d';ctx.lineWidth=3;const text=(guideBoss?'BOSS · ':'COFFRE · ')+Math.round(Math.hypot(c.x-p.x,c.y-p.y)/10)+' m';ctx.strokeText(text,x,y+24);ctx.fillText(text,x,y+24);}}}const grad=ctx.createRadialGradient(view.w/2,view.h/2,Math.min(view.w,view.h)*.2,view.w/2,view.h/2,Math.max(view.w,view.h)*.7);grad.addColorStop(0,'#31270f00');grad.addColorStop(1,'#31270f2c');ctx.fillStyle=grad;ctx.fillRect(0,0,view.w,view.h);ctx.restore();}
function input(){const x=(keys.has('arrowright')||keys.has('d')?1:0)-(keys.has('arrowleft')||keys.has('q')||keys.has('a')?1:0)+joy.x,y=(keys.has('arrowdown')||keys.has('s')?1:0)-(keys.has('arrowup')||keys.has('z')||keys.has('w')?1:0)+joy.y;if(x||y)lastDirection={x,y};return {x,y};}
function frame(t){const dt=Math.min(.05,(t-last)/1000||0);last=t;game.update(dt,input());audio.tick(dt,game);draw(dt);hudClock+=dt;if(hudClock>.1){updateHud();hudClock=0;}requestAnimationFrame(frame);}requestAnimationFrame(frame);
document.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey)return;const key=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(key))e.preventDefault();if(e.repeat&&[' ','escape','enter'].includes(key))return;if(key==='escape'){if(game.status==='loot')game.continueLoot();else togglePause();return;}if(key==='e'&&game.status==='playing'){game.openChest();return;}if(key==='enter'&&game.status==='worldclear'){game.nextWorld();return;}if(key==='enter'&&game.status==='loot'){game.continueLoot();return;}if(key===' '){game.dash(lastDirection.x,lastDirection.y);return;}if(game.status==='upgrade'&&['1','2','3','&','é','"'].includes(key)){const idx={'1':0,'2':1,'3':2,'&':0,'é':1,'"':2}[key];if(game.choices[idx])game.choose(game.choices[idx].id);return;}if(key==='enter'&&game.status==='ready'){start();return;}if(key==='enter'&&['won','dead'].includes(game.status)){start();return;}if(key==='enter'&&game.status==='paused'){togglePause();return;}if(['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d','z','q'].includes(key))keys.add(key);});document.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();joy={x:0,y:0};if(game.status==='playing')togglePause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&game.status==='playing')togglePause();});$('pause').onclick=togglePause;
$('sound').onclick=()=>{sound=!sound;audio.setEnabled(sound);$('sound').innerHTML=`♪ <span>SON ${sound?'ON':'OFF'}</span>`;$('sound').setAttribute('aria-label',sound?'Couper le son':'Activer le son');$('sound').title=sound?'Couper le son':'Activer le son';if(sound)audio.unlock().then(()=>audio.effect('pickup')).catch(()=>{});};
$('interact').onclick=()=>game.openChest();$('chestTouch').onpointerdown=e=>{e.preventDefault();game.openChest();};
const joystick=$('joystick'),stick=$('stick');let joyPointer=null;function setJoy(e){const r=joystick.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,len=Math.hypot(dx,dy),max=r.width*.34,factor=len>max?max/len:1;joy={x:dx*factor/max,y:dy*factor/max};stick.style.transform=`translate(${dx*factor}px,${dy*factor}px)`;}joystick.onpointerdown=e=>{e.preventDefault();joyPointer=e.pointerId;joystick.setPointerCapture(e.pointerId);setJoy(e);};joystick.onpointermove=e=>{if(e.pointerId===joyPointer)setJoy(e);};function releaseJoy(){joyPointer=null;joy={x:0,y:0};stick.style.transform='';}joystick.onpointerup=releaseJoy;joystick.onpointercancel=releaseJoy;joystick.onlostpointercapture=releaseJoy;$('dashTouch').onpointerdown=e=>{e.preventDefault();game.dash(lastDirection.x,lastDirection.y);};
const registry=document.modelContext;if(registry?.registerTool){const lifecycle=new AbortController();const tools=[{name:'read_cactocalypse_run',description:'Read the current Cactocalypse run, including offered mutations.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>game.snapshot()},{name:'start_cactocalypse_run',description:'Start or restart an expedition with an optional cactus character. Resets the current run.',inputSchema:{type:'object',properties:{character:{type:'string',enum:CHARACTERS.map(c=>c.id)}},additionalProperties:false},execute:(input={})=>{if(!loaded)throw new Error('Les images chargent encore');if(input.character!==undefined){if(!CHARACTERS.some(c=>c.id===input.character))throw new Error('Cactus inconnu');selectedCharacter=input.character;}start();return game.snapshot();}},{name:'open_nearby_cactocalypse_chest',description:'Spend run gold to open the nearest chest within reach and equip its random item.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>({...game.openChest(),run:game.snapshot()})},{name:'continue_cactocalypse_world',description:'Enter the next world after defeating its boss, keeping the inventory.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{if(!game.nextWorld())throw new Error('Le boss doit être vaincu');return game.snapshot();}},{name:'continue_cactocalypse_loot',description:'Close the loot presentation and resume the expedition.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{game.continueLoot();return game.snapshot();}},{name:'choose_cactocalypse_mutation',description:'Choose one currently offered mutation and resume the run.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},execute:input=>{if(!input||typeof input.id!=='string')throw new Error('Identifiant requis');game.choose(input.id);return game.snapshot();}}];for(const tool of tools){try{Promise.resolve(registry.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
